version: '3.8'

services:
  db:
    image: mysql:8.0.34
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_name
    ports:
      - "3306:3306"
